### PR TITLE
Adding a docker-compose v2 example

### PR DESCRIPTION
**Pull request by sfdye**
Took me a while to make it work with my current docker compose setup. 

This PR provides a working example to use `neilpang/nginx-proxy` image in a docker-compose file.

### CODE REVIEW

**Comment by sfdye** [comment]
Thanks! I will try to use this in our cookiecutter-django project to get rid of caddy.

https://github.com/pydanny/cookiecutter-django/pull/1282

**Comment by Neilpang** [comment]
enjoy.

**Comment by CHN-STUDENT** [comment]
@Neilpang Hope you can update this project follow it source project ? The source project fixed some bugs by update, so could you update this project follow it if you are free? Thanks!!

**Comment by Neilpang** [comment]
@CHN-STUDENT  updated, please try again.

**Pull request merged**
